questions = [
    "How install global search in creatio?",
    "How can I switch Classic UI to Freedom?",
    "is possible for us set up an external identity system, not ADSF or SignOne? The provider is using SAML 2.0",
    "Could you please give us instructions(how to use it and configure) regarding the chatGPT.",
    "Is it possible to Remove/Edit/Hide certain fields from appearing in the Opportunity Timeline?",
    "our onprem customer DMH wants to connect their Creatio to cloud Exchange (MS365). The admin asked, which ports we need in the firewall to do that?",
    "Де налаштовуються сповіщення користувачам? Сповіщення про нове завдання на них, новий лід, повідомлення в стрічці з новинами компанії, тощо.",
    "Як в Журналі змін об'єкта дізнатися які саме поля правились?",
    "Як налаштувати авторизацію користувачів в додатку Creatio через Microsoft365 (Azure Active Directory)",
    "Як можна додати маску для телефонного номеру на Classic UI?",
    "Как изменить назвние раздела?",
    "How to configure mobile notification in creatio? Please advise, thanks a lot",
    "При спробі додати Фейсбук або лінкедін як засіб зв'язку контрагента система видає вікно авторизаці фейсбук/лінкедін. Це так має бути?",
    "What is the difference between Classic and Freedom UI?",
]